print("TOKO MAINAN ANAK")
print("================================================")
nama_pembeli=input("Masukan nama pembeli : ")
kode_mainan=input("Masukan kode maianan : ")
harga=input('masukan harga : ')
jumlah=input('masukan jumlah beli : ')
print("================================================")
print('nama pembeli = '+nama_pembeli)
print('kode mainan = '+ kode_mainan)
print('harga = '+ harga)
print('jumlah beli = ', int(jumlah))
print('total = ',int(harga)*int(jumlah))
